/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KioskIndexRouteImport } from './routes/kiosk.index'
import { Route as KioskLoggedRouteImport } from './routes/kiosk.logged'
import { Route as KioskLogRouteImport } from './routes/kiosk.log'
import { Route as ApiKioskSubmitRouteImport } from './routes/api/kiosk/submit'
import { Route as ApiKioskSessionRouteImport } from './routes/api/kiosk/session'
import { Route as ApiKioskMembersRouteImport } from './routes/api/kiosk/members'
import { Route as ApiKioskExercisesRouteImport } from './routes/api/kiosk/exercises'

const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskIndexRoute = KioskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KioskRoute,
} as any)
const KioskLoggedRoute = KioskLoggedRouteImport.update({
  id: '/logged',
  path: '/logged',
  getParentRoute: () => KioskRoute,
} as any)
const KioskLogRoute = KioskLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => KioskRoute,
} as any)
const ApiKioskSubmitRoute = ApiKioskSubmitRouteImport.update({
  id: '/api/kiosk/submit',
  path: '/api/kiosk/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKioskSessionRoute = ApiKioskSessionRouteImport.update({
  id: '/api/kiosk/session',
  path: '/api/kiosk/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKioskMembersRoute = ApiKioskMembersRouteImport.update({
  id: '/api/kiosk/members',
  path: '/api/kiosk/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKioskExercisesRoute = ApiKioskExercisesRouteImport.update({
  id: '/api/kiosk/exercises',
  path: '/api/kiosk/exercises',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kiosk': typeof KioskRouteWithChildren
  '/kiosk/log': typeof KioskLogRoute
  '/kiosk/logged': typeof KioskLoggedRoute
  '/kiosk/': typeof KioskIndexRoute
  '/api/kiosk/exercises': typeof ApiKioskExercisesRoute
  '/api/kiosk/members': typeof ApiKioskMembersRoute
  '/api/kiosk/session': typeof ApiKioskSessionRoute
  '/api/kiosk/submit': typeof ApiKioskSubmitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kiosk/log': typeof KioskLogRoute
  '/kiosk/logged': typeof KioskLoggedRoute
  '/kiosk': typeof KioskIndexRoute
  '/api/kiosk/exercises': typeof ApiKioskExercisesRoute
  '/api/kiosk/members': typeof ApiKioskMembersRoute
  '/api/kiosk/session': typeof ApiKioskSessionRoute
  '/api/kiosk/submit': typeof ApiKioskSubmitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kiosk': typeof KioskRouteWithChildren
  '/kiosk/log': typeof KioskLogRoute
  '/kiosk/logged': typeof KioskLoggedRoute
  '/kiosk/': typeof KioskIndexRoute
  '/api/kiosk/exercises': typeof ApiKioskExercisesRoute
  '/api/kiosk/members': typeof ApiKioskMembersRoute
  '/api/kiosk/session': typeof ApiKioskSessionRoute
  '/api/kiosk/submit': typeof ApiKioskSubmitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kiosk'
    | '/kiosk/log'
    | '/kiosk/logged'
    | '/kiosk/'
    | '/api/kiosk/exercises'
    | '/api/kiosk/members'
    | '/api/kiosk/session'
    | '/api/kiosk/submit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kiosk/log'
    | '/kiosk/logged'
    | '/kiosk'
    | '/api/kiosk/exercises'
    | '/api/kiosk/members'
    | '/api/kiosk/session'
    | '/api/kiosk/submit'
  id:
    | '__root__'
    | '/'
    | '/kiosk'
    | '/kiosk/log'
    | '/kiosk/logged'
    | '/kiosk/'
    | '/api/kiosk/exercises'
    | '/api/kiosk/members'
    | '/api/kiosk/session'
    | '/api/kiosk/submit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KioskRoute: typeof KioskRouteWithChildren
  ApiKioskExercisesRoute: typeof ApiKioskExercisesRoute
  ApiKioskMembersRoute: typeof ApiKioskMembersRoute
  ApiKioskSessionRoute: typeof ApiKioskSessionRoute
  ApiKioskSubmitRoute: typeof ApiKioskSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk/': {
      id: '/kiosk/'
      path: '/'
      fullPath: '/kiosk/'
      preLoaderRoute: typeof KioskIndexRouteImport
      parentRoute: typeof KioskRoute
    }
    '/kiosk/logged': {
      id: '/kiosk/logged'
      path: '/logged'
      fullPath: '/kiosk/logged'
      preLoaderRoute: typeof KioskLoggedRouteImport
      parentRoute: typeof KioskRoute
    }
    '/kiosk/log': {
      id: '/kiosk/log'
      path: '/log'
      fullPath: '/kiosk/log'
      preLoaderRoute: typeof KioskLogRouteImport
      parentRoute: typeof KioskRoute
    }
    '/api/kiosk/submit': {
      id: '/api/kiosk/submit'
      path: '/api/kiosk/submit'
      fullPath: '/api/kiosk/submit'
      preLoaderRoute: typeof ApiKioskSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kiosk/session': {
      id: '/api/kiosk/session'
      path: '/api/kiosk/session'
      fullPath: '/api/kiosk/session'
      preLoaderRoute: typeof ApiKioskSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kiosk/members': {
      id: '/api/kiosk/members'
      path: '/api/kiosk/members'
      fullPath: '/api/kiosk/members'
      preLoaderRoute: typeof ApiKioskMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kiosk/exercises': {
      id: '/api/kiosk/exercises'
      path: '/api/kiosk/exercises'
      fullPath: '/api/kiosk/exercises'
      preLoaderRoute: typeof ApiKioskExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KioskRouteChildren {
  KioskLogRoute: typeof KioskLogRoute
  KioskLoggedRoute: typeof KioskLoggedRoute
  KioskIndexRoute: typeof KioskIndexRoute
}

const KioskRouteChildren: KioskRouteChildren = {
  KioskLogRoute: KioskLogRoute,
  KioskLoggedRoute: KioskLoggedRoute,
  KioskIndexRoute: KioskIndexRoute,
}

const KioskRouteWithChildren = KioskRoute._addFileChildren(KioskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KioskRoute: KioskRouteWithChildren,
  ApiKioskExercisesRoute: ApiKioskExercisesRoute,
  ApiKioskMembersRoute: ApiKioskMembersRoute,
  ApiKioskSessionRoute: ApiKioskSessionRoute,
  ApiKioskSubmitRoute: ApiKioskSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
